name: FreeBSD update
run-name: create diff for updating FreeBSD port
on: [workflow_dispatch]
jobs:
  Update-on-x86:
    runs-on: ubuntu-latest
    name: create diff
    steps:
    - uses: actions/checkout@v4
    - name: create diff for FreeBSD port update
      uses: vmactions/freebsd-vm@v1
      with:
        prepare: |
          pkg install -y git
        run: |
          cd freebsd && ./update.sh
    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: diffs
        path: |
          ${{ github.workspace }}/freebsd/Makefile
          ${{ github.workspace }}/freebsd/adjuster.mbox
  Test-on-ARM:
    runs-on: ubuntu-24.04-arm
    name: test on ARM Ubuntu
    steps:
    - name: test if FreeBSD can work in ARM
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        arch: aarch64
        run: |
          env
          freebsd-version
          sysctl hw.model
          sysctl hw.ncpu
          sysctl hw.physmem
          sysctl hw.usermem
